## Assignment 5: Customer Segmentation using SVM

### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

### Loading the Dataset

In [2]:
iris = load_iris()
X = iris.data
y = iris.target

### Dataset Summary

In [13]:
print("Shape:", X.shape)
print("Feature names:", iris.feature_names)
print("Class distribution:")
unique, counts = np.unique(y, return_counts=True)
for i in range(len(unique)):
    print(f"Class {unique[i]}: {counts[i]} samples")

Shape: (150, 4)
Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Class distribution:
Class 0: 50 samples
Class 1: 50 samples
Class 2: 50 samples


### Train-Test Split (70:30)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 105
Testing samples: 45


### Feature Scaling

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Training SVM with Linear Kernel

In [21]:
svm_linear = SVC(kernel='linear')
svm_linear.fit(X_train, y_train)
y_pred_linear = svm_linear.predict(X_test)

### Linear Kernel Results

In [22]:
print("Accuracy:", accuracy_score(y_test, y_pred_linear))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_linear))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_linear))

Accuracy: 0.9777777777777777

Confusion Matrix:
[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



### Training SVM with RBF Kernel

In [23]:
svm_rbf = SVC(kernel='rbf')
svm_rbf.fit(X_train, y_train)
y_pred_rbf = svm_rbf.predict(X_test)

### RBF Kernel Results

In [24]:
print("Accuracy:", accuracy_score(y_test, y_pred_rbf))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rbf))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rbf))

Accuracy: 1.0

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



### Comparison

Since,Accuracy of RBF Kernel is greater than Linear Kernel,Linnear Kernel is better.